ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*
BOARDS_TXT = /usr/share/arduino/hardware/arduino/boards.txt
ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/cores/arduino
ARDUINO_PLATFORM_LIB_PATH = /usr/share/arduino/libraries
ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino/variants
BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino/bootloaders

ARDUINO_SKETCHBOOK = /home/sean/sketchbook
USER_LIB_PATH = /home/sean/sketchbook/libraries
BOARD_TAG = uno

include /home/sean/Arduino-Makefile/Arduino.mk
